config/routes.rb
TodoList::Application.routes.draw do

  root to: 'projects#index'

  resources :projects do
    resources :tasks do
    	member do
    		put :up
    		put :down
    	end
    end
  end
put '/task/:id/checkbox', to: "tasks#checkbox"
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
		belongs_to :project

		before_create :setup_priority

		validates :name, presence: true
		validates_uniqueness_of :name, scope: :project_id
		
	def up
		if victim = Task.where(project_id: self.project_id, priority: (self.priority+1)).first
			self.priority, victim.priority = victim.priority, self.priority
			self.save
			victim.save
		end
	end

	def down
		if victim = Task.where(project_id: self.project_id, priority: (self.priority-1)).first
			self.priority, victim.priority = victim.priority, self.priority
			self.save
			victim.save
		end
	end

	def setup_priority
		task = Task.where(project_id: self.project_id).order(priority: :desc).first
			self.priority=if task
			task.priority + 1
		else
			0
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

def index
   @projects = Project.all.to_a
   @project_new = Project.new
   @task_new = Task.new
end

def create
	@project = Project.create!(params.require(:project).permit(:name))
	@task_new = Task.new
	render partial: 'project', locals: {project: @project}, layout: false
end

def destroy
	Project.find(params[:id]).destroy
	render nothing: true	
end

def edit
	@project = Project.find(params[:id])
end

def update
	if Project.find(params[:id]).update_attributes(params.permit(:name))
		render nothing: true
	else
		render nothing: true, status: 422	
	end
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create
		@task = Task.create!(params.require(:task).permit(:name, :project_id))
		render partial: 'tasks/task_form', locals: {project: @task.project, task: @task}, layout: false and return if request.xhr?
	end

	def destroy
		Task.find(params[:id]).destroy
		render nothing: true
	end

	def checkbox
		@task = Task.find(params[:id])
		@task.status ^= true
		@task.save!
		render nothing: true
	end

	def update
		if Task.find(params[:id]).update_attributes(params.permit(:name, :deadline))
			render nothing: true
		else
			#Implement sending error header and procesing it in javascript event listener
		end
	end

	def up
		Task.where(id:params[:id]).first.up
		render nothing: true
	end

	def down
		Task.where(id:params[:id]).first.down
		render nothing: true
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 align="center" class="header_font"> TODO List </h1>

  	<div class="container">
		<%= yield %>
	</div>
<div id="end"></div>
</body>
</html>

app/views/projects/_project.html.erb
    <div class="span8 task_container">
        <div class="project_name background">
        <div style="height: 15px;"></div>
            <i class="icon-list-alt icon-2x" style="display:inline; padding-left:9px;">
            <span class="project_text" data-url="/projects/<%=project.id%>"> <%= project.name %> </span>
            </i>
            
            <div class="block" style="float: right; margin-right: 20px;">
                <a href='#' class='edit_project_link icon-pencil icon-2x black'></a>
                 <span style="margin-left: 10px; font-size: 20px;"> | </span>
                 <%= link_to '', project_path(project), remote: true, 
                                                        method: :delete, 
                                                        class: "delete_project icon-trash icon-2x black", 
                                                        data: {confirm: 'Are you sure?'} %>
            </div>
        </div>
        <div style="background-color: #DEDEDE; position: relative;" >
            <i class="icon-plus icon-2x plus"></i>
            <div class="input-append input_form new_task input_form">
        <%= form_for [project, @task_new], remote: true do |form| %>
                <%= form.hidden_field :project_id, value: project.id %>
                <div class="span6" id="appendedInputButtons">
                    <%= form.text_field :name, class: "span6" %>
                    <button class="btn btn-primary" type="submit">Add Task</button>
                </div>
        <%end%>
            </div>
        </div>
        <%= render 'tasks/tasks_form', project: project %>
    </div>

app/views/projects/_projects.html.erb
<div class="projects_container">
	<%= render partial: 'project', collection: @projects %>
</div>

app/views/projects/index.html.erb
<%= render 'projects' %>
    <div id='follow'>
		<%= form_for @project_new, remote: true do |f| %>
		<span class="input-append" align: "ceneter">
			<%= f.text_field :name %>
			<button type="submit" class="btn btn-inverse" align="ceneter" >Create Project</button>
		</span>
		<%end%>
    </div>

app/views/tasks/_task_form.html.erb
    <tbody class="background task">
        <th>
            <span>
                <input type="checkbox" <%= "checked" if task.status %> class="status_ok<%=" put_ok" if task.status%>" data-id="<%=task.id%>">
            </span>
        </th>
        <th width="460px">
            <div>
                <p class="task_title" 
                data-url="/projects/<%=project.id%>/tasks/<%=task.id%>"
                style="display: inline; font-size: 16px;"><%= task.name %></p>
                <span class="deadline" style="float: right">
                    <a href="#" class="take_deadline black" data-type="date" 
                                data-url="/projects/<%=project.id%>/tasks/<%=task.id%>">
                                <% if task.deadline.nil? %>
                                <i class="icon-calendar" style="color: rgb(51, 51, 51);"></i>
                                <% else %>
                                    <% if task.deadline < Time.now %>
                                    <p style="color: red; margin: 0;"><%= task.deadline.strftime("%d/%m/%Y") %></p>
                                    <% else %>
                                    <%= task.deadline.strftime("%d/%m/%Y") %>
                                    <% end %>
                                <% end %></a>
                </span>
            </div>
         </th>
            <th>
            <div style="float: right; font-size: 16px;" class="block">
            <%= link_to "", up_project_task_path(project, task), method: :put, 
                class: "up icon-arrow-up black", remote: true %>
            <%= link_to "", down_project_task_path(project, task), method: :put, 
                class: "down icon-arrow-down black", remote: true %> |
            <a href='#' class="edit_task_link icon-pencil black"></a> |
            <%= link_to "", project_task_path(project, task),remote: true, 
                                                            method: 'delete', 
                                                            class: "delete_task icon-trash black",
                                                            data: {confirm: 'Are you sure?'} %>
            </div>
        </th>
    </tbody>

app/views/tasks/_tasks_form.html.erb
<div>
    <table class="table table-bordered tasks_form">
	<% project.tasks.order('priority DESC').each do |task| %>
    	<%= render 'tasks/task_form', project: project, task: task %>
    <% end %>
    </table>
</div>